### ISSUE TITLE
Piper voices will not read sign-in and secure screens unless the piper-grpc file is coppied manually to the appropriate folder in the NVDA System configuration directory.

### ISSUE THREAD

**Issue by mikebayus** [mush42/piper-nvda#21]
If I want my Piper TTS voice to read secure Screens, I need to copy the piper-grpc executable in to the appropriate Piper Addon folder in the System Config directory after I exit out of the "use current settings to read user account and secure screens butten.

If I don't copy the file, I get Microsoft David, as Piper won't load.

**Comment by mush42** [comment]
Hi @mikebayus  isn't this the default NVDA behavior with all add-on based synthesizers?

**Comment by ChrisDuffley** [comment]
@mush42 No it is not. Every other synthesizer like Eloquence or Vocalizer has their files copied to the system config when this is executed.

**Comment by mikebayus** [comment]
Acapela does not either.

Files need to be coppied manually, and I don't like it.

If vocalizer can do it why can't we?

How can we fix it?
