### ISSUE TITLE
Instructions for downloading and installing a voice are no longer valid

### ISSUE THREAD

**Issue by accdc** [mush42/piper-nvda#22]
Hello,
I've been trying to get this working for days now and it seems to be impossible.

After starting NVDA after the plug-in is installed, I get a notice saying that there are no Piper voices installed and to download a voice.

After following the instructions and going to the download page, there is no option to download a packaged tar.gz file to install a voice. E.G. Amy low quality. The only downloads are individual .onnx and .onnx.json files.

I thought I could simply download these files individually and package them myself within my own tar.gz file, but every attempt I've made to do this throws an error when I try to import it within the plug-in interface.

Can you tell me how to manually install the .onnx and .onnx.json files so I can bypass the tar.gz file import?

That or where I can download these as valid packages?

Thanks,
Bryan

**Comment by accdc** [comment]
As a quick update, I updated my plug-in version to the latest beta 2 released  about 5 days ago, and was able to import the voices for Amy Low and Medium.

However it is still impossible to run the voices.

When I open the Speech panel within NVDA, and activate Change to choose the Piper TTS Synth, there is no such option and nothing else that looks like it will run these voices.

Is this setting somewhere else in the UI?


Thanks,
Bryan

**Comment by mush42** [comment]
@accdc  there is now an integrated voice manager which handles downloading voices for you. Make sure to use the latest version of the add-on.

And sorry for the out-of-date docs.

**Comment by mush42** [comment]
I'll come back to the docs after I finish the code.

Unfortunately, this add-on is a one-man-show 🤷

**Comment by accdc** [comment]
Thanks, I know what you mean about being a one-man show, I've been solely working on Apex 4X for years.

I was able to get it working, seems like there was a conflict with the prior drivers that was causing it to fail, so I manually deleted all of the plug-in files and reinstalled everything. The Amy synth wasn't actually in the download list, so I manually bundled the files into a tar.gz file and installed it manually instead.

It sounds great in NVDA. Do you know if it is possible to get this working with SAPI so it can be used with Narrator and JAWS too?

All the best,
Bryan

**Comment by mush42** [comment]
@accdc  this is in my TodoList. But now I'm focusing on fixing the latency issue, and the remaining bugs in the add-on.

**Comment by accdc** [comment]
I understand, thanks. When it's possible to use it at the same level as Narrator it will take off everywhere. The voices really are amazing. :)
