### ISSUE TITLE
New Piper TTS Voice for NVDA

### ISSUE THREAD

**Issue by mikebayus** [mush42/piper-nvda#26]
Hi all.

I am enjoying using this add-on for the NVDA Screen reader.

I am running Windows 11 latest build, and I have just downloaded the latest voussion of the NVDA Screen Reader, V2023.3.

I have always like the voice of a Librivox reader called Amanda Friday.

Would it be possible to add her voice to the list of voices?

Here is a link where you can listen to her read.

https://librivox.org/screen-acting-by-mae-marsh/

I really really like her voice.

Thanks in advance.

**Comment by mush42** [comment]
@mikebayus 
We're glad that you like piper-for-NVDA.

Unfortunately, we don't have the hardware resources to train a voice. 

If you have the skills, you can try fine tuning an existing voice to this dataset using Google Colab.

Please checkout this guide for more information:

https://github.com/ZachB100/Piper-Training-Guide-with-Screen-Reader/blob/main/README.md

**Comment by rmcpantoja** [comment]
Yeah we can fine-tune this voice, it can be great for read another
audiobooks or make audio-movies as well. Sounds great.

**Comment by mikebayus** [comment]
Thanks for the link.

It will be most helpfull.
