### ISSUE TITLE
Piper TTS voices make a "puffing" sound instead of  pronouncing the letter "L" as well as some punctuation marks.

### ISSUE THREAD

**Issue by mikebayus** [mush42/piper-nvda#27]
Hi,

I haven't reported this as I have used the Piper TTS Voices Add-on for NVDA as I thought that others might have already reported this, but as I found no other issue I am reporting this now.

When I use left and right arrows to scrole character by character, the letter "l makes a "puffing sound" rather than pronouncing the letter "l".

Try the word:  "alleluia".

Some punctuation marks do this as well.

As I write this, I just had my Piper voice read the lines that had just the letter "l" in them and my voice parces the letter "l in the case of reading a sentence, it's just when using left and right arrows to scrole one letter at a time.

**Comment by rmcpantoja** [comment]
Hi,
Unfortunately, unclear pronunciations are a defect of the VITS model. In this case, you could add slightly shorter audios to the dataset, and train it a little more. It can surely improve efficiency even for reading extremely short texts. It should be noted that efficiency is more notable in medium quality models.

**Comment by mikebayus** [comment]
I find pronunciation to be very clear and easily understood, and the
reading styles of each of the different voices to be conversational.

My issue is the sound that the voices make when scroling letter by letter
and saying the letter "l".

try reading this using the NVDA Screen Reader, and using the right and left
arrows to spell the word "scroling.

Every letter is pronounced correctly except the letter "L".

As I say some punctuation marks make the same puffing sound instead of
saying their names.

**Comment by mush42** [comment]
Hi @mikebayus 
Unfortunately, we can do nothing about this.
This is not an issue of the add-on per se, it is an issue of the underlying model and the dataset used to train it.

**Comment by mush42** [comment]
@mikebayus 
Most of these voices are not designed with screen reader use in mind.
The add-on itself can drive any piper-compatible model. I see no reason that our community comes together and create a dataset for screen readers and train a voice based on it.
