### ISSUE TITLE
NVDA V2024.1-Beta1 is now out therefore Piper TTS v2.0-beta2 is broken.

### ISSUE THREAD

**Issue by mikebayus** [mush42/piper-nvda#32]
Is there any chance we can soon have Piper TTS for NVDA v2.0-beta3/

**Comment by mush42** [comment]
yes. I'm working on that.

**Comment by mikebayus** [comment]
Any Idea as to how soon we can expect a new version?

Keep on keeping on, and keep up the good work.

I am very pleased with the Add-on so far, and I reverted back to NVDA v2023.3 just so I could keep it.

I really like NVDA 2024.1, at least the Beta versions, but I missed my Piper voice.

**Comment by mush42** [comment]
Hi @mikebayus 

Thanks for your interest.
I'll push support soon.

Best
