### ISSUE TITLE
How to package streamable voices

### ISSUE THREAD

**Issue by pvagner** [mush42/piper-nvda#35]
Please can you give me a hint on how to package the streaming capable voices?
I have managed to pick this piper pull request https://github.com/rhasspy/piper/pull/255 and export the trained voice into onnx.

**Comment by rmcpantoja** [comment]
Hi,
As the streaming feature isn't merged to the main repository, I can't update the model exporter notebook (if you're using this to export models) Unless I merge the straming PR to my repository where I have the notebooks, but it would be a duplicate pull request.

**Comment by pvagner** [comment]
Hello,
I am calling the python script directly:
```
python3 -m piper_train.export_onnx_streaming \
    /home/user/piper/training/model/lightning_logs/version_1/checkpoints/*.ckpt \
    /home/user/piper/training/model-streaming-unoptimized.onnx
```
The folder /home/user/piper/training/model-streaming-unoptimized.onnx contains two files decoder.onnx and encoder.onnx. I do also have a corresponding json file with the configuration.
I simply need to know what's the folder layout so the addon will recognize this as a working voice.
Before introducing streaming support the json and onnx files were stored inside the folder with the same name as the basename of both these files with file extensions stripped out. Now when considering streaming where do I put decoder.onnx and encoder.onnx files in relation to the json file?
Is there an example voice someone else has created so I can see it in action?

**Comment by mush42** [comment]
Hi all

I've re-exported most of available Piper's voices to the Real-time format.

You can find them under this [Huggingface repo](https://huggingface.co/datasets/mush42/piper-rt/tree/main/)

Best
Musharraf

**Comment by pvagner** [comment]
Huge thanks. I have realized the addon can't yet handle these voices.
