### ISSUE TITLE
Possibility to add voice trainer directly to the add-on

### ISSUE THREAD

**Issue by Tetrismonster** [mush42/piper-nvda#36]
Hey.
Would it be possible to add the ability to train a voice directly within the add-on for those of us who aren't confident with the other methods?

**Comment by mush42** [comment]
Hi

I don't think it'll be feasible to include training scripts and libraries within the add-on.

**Comment by Elshara** [comment]
Perhaps an add on to include this functionality would go hand in hand with this...I think it would really make something cool happen for instance like a voice generator like the designer Eleven Labs has.
